//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Divar.Core.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DivarEntities : DbContext
    {
        public DivarEntities()
            : base("name=DivarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Statistic> Statistics { get; set; }
        public virtual DbSet<TBL_Advertisement> TBL_Advertisement { get; set; }
        public virtual DbSet<TBL_AdvertisementType> TBL_AdvertisementType { get; set; }
        public virtual DbSet<TBL_AdvertiserType> TBL_AdvertiserType { get; set; }
        public virtual DbSet<TBL_Assembler> TBL_Assembler { get; set; }
        public virtual DbSet<TBL_City> TBL_City { get; set; }
        public virtual DbSet<TBL_Color> TBL_Color { get; set; }
        public virtual DbSet<TBL_Employment> TBL_Employment { get; set; }
        public virtual DbSet<TBL_Image> TBL_Image { get; set; }
        public virtual DbSet<TBL_Manufacturer> TBL_Manufacturer { get; set; }
        public virtual DbSet<TBL_Product> TBL_Product { get; set; }
        public virtual DbSet<TBL_Service> TBL_Service { get; set; }
        public virtual DbSet<TBL_State> TBL_State { get; set; }
        public virtual DbSet<TBL_Vehicle> TBL_Vehicle { get; set; }
        public virtual DbSet<TBL_VehicleType> TBL_VehicleType { get; set; }
    }
}
