//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Divar.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Advertisement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Advertisement()
        {
            this.TBL_Employment = new HashSet<TBL_Employment>();
            this.TBL_Image = new HashSet<TBL_Image>();
            this.TBL_Product = new HashSet<TBL_Product>();
            this.TBL_Service = new HashSet<TBL_Service>();
        }
    
        public int Id { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string UserID { get; set; }
        public string Description { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual TBL_City TBL_City { get; set; }
        public virtual TBL_Vehicle TBL_Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Employment> TBL_Employment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Image> TBL_Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Product> TBL_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Service> TBL_Service { get; set; }
    }
}
